export const CategoryList = [
  { number: 0, name: "All Categories" },
  { number: 3, name: "Arts & Entertainment" },
  { number: 47, name: "Autos & Vehicles" },
  { number: 44, name: "Beauty & Fitness" },
  { number: 22, name: "Books & Literature" },
  { number: 12, name: "Business & Industrial" },
  { number: 5, name: "Computers & Electronics" },
  { number: 7, name: "Finance" },
  { number: 71, name: "Food & Drink" },
  { number: 8, name: "Games (incl. Video Games)" },
  { number: 45, name: "Health" },
  { number: 65, name: "Hobbies & Leisure" },
  { number: 11, name: "Home & Garden" },
  { number: 13, name: "Internet & Telecom" },
  { number: 958, name: "Jobs & Education" },
  { number: 19, name: "Law & Government" },
  { number: 16, name: "News" },
  { number: 299, name: "Online Communities" },
  { number: 14, name: "People & Society" },
  { number: 66, name: "Pets & Animals" },
  { number: 29, name: "Real Estate" },
  { number: 533, name: "Reference" },
  { number: 174, name: "Science" },
  { number: 18, name: "Shopping" },
  { number: 20, name: "Sports" },
  { number: 67, name: "Travel" },
];
